name:                bytecode-parser
version:             1.0.0.0
github:              "mbrc12/bytecode-parser"
license:             BSD3
author:              "Mriganka Basu Roy Chowdhury"
maintainer:          "mbrc12@gmail.com"
copyright:           "2018 Mriganka Basu Roy Chowdhury"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        A simple JVM Bytecode (.class) parser
dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10
- directory >= 1.3
- filepath >= 1.4
- yaml >= 0.8.20
- bytestring
- vector >= 0.12
- binary
- text >= 1.2.2.2
- STMonadTrans 
- transformers >= 0.5

library:
  source-dirs: src
 
executables:
    bptester:
        main:           Main.hs
        source-dirs:    app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -funbox-strict-fields
        dependencies:
            - bytecode-parser

tests:
  bytecode-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytecode-parser
